"""add rbac tables

Revision ID: 0983986b3ee1
Revises: 
Create Date: 2026-07-20 19:17:23.229596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0983986b3ee1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'rooms', ['room_name'])
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.drop_index(op.f('ix_users_user_id'), table_name='users')
    # op.create_unique_constraint(None, 'users', ['email'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['role_id'])
    # op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'rooms', type_='unique')
    # ### end Alembic commands ###
